version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

jobs:
  aws-example:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: "example-session"
          session-duration: "1800"
      - run:
          name: Log-into-AWS-ECR
          command: |
            aws ecr get-login-password

workflows:
  OIDC-with-AWS:
    jobs:
      - aws-example
