version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

jobs:
  aws-example:
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: "example-session"
          session-duration: "1800"
      - run:
          name: List S3 buckets
          command: aws s3 ls

workflows:
  OIDC-with-AWS:
    jobs:
      - aws-example
