apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: yes1
  name: yes1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yes1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yes1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
