apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluegreen-test
      colour: green
  template:
    metadata:
      labels:
        app: bluegreen-test
        colour: green
    spec:
      containers:
      - name: nginx
        image: linuxacademycontent/ckad-nginx:green
        ports:
        - containerPort: 80