apiVersion: apps/v1
kind: Deployment
metadata:
  name: ly-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: "key"
        operator: "Exists"
        effect: "NoSchedule"